import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Script from 'next/script'

export default function Home() {
  const [progress, setProgress] = useState("-")

  return (
    <div className={styles.container}>
      <Head>
        <title>S³</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script 
        id="stripe-js"
        onLoad={() => {
          console.log("progress ?");
          setProgress(localStorage.getItem("progress"));
        }}      
      />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Márovče,
        </h1>

        <p className={styles.description}>
          naše výprava tě již očekává.
        </p>
        <p>
          Fáze: {progress}
        </p>

        <div className={styles.grid}>
          <a href="./stage1" className={styles.card}>
            <h2>Fáze 1 &rarr;</h2>
            <h3>Začátek pátrání</h3>
            <p>Připrav se nebude to jednoduché! Máme zprávy že artefakt se nachází ...</p>
          </a>

          <a href="./stage2" className={styles.card}>
            <h2>Fáze 2 &rarr;</h2>
            <h3>Ztracený artefakt</h3>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="./stage3" className={styles.card}>
            <h2>Fáze 3 &rarr;</h2>
            <h3>Neuvěřitelný poklad</h3>
            <p>Artefakt obsahoval neskutečný poklad</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            
          </span>
        </a>
        <a href="./reset"> Reset</a>
      </footer>
    </div>
  )
}
