import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

    function resetProgress(e) {
        // e.preventDefault();
        console.log('Progress reset');
        localStorage.setItem("progress","1");
        document.getElementById("btnexit").click()
      }
    function setProgress(e) {
        // e.preventDefault();
        console.log('Progress reset');
        localStorage.setItem("progress","2");
        document.getElementById("btnexit").click()
      }

    
  return (
    <div className={styles.container}>
      <Head>
        <title>S³</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
          <button className={styles.card} onClick={resetProgress}>
            <h2>Restartovat ?</h2>
            <p>
            Vymazat progress hry a začít znovu.
            </p>
          </button>
        <a id="btnexit" href="./" ></a>
        </div>
      </main>
      <footer className={styles.footer}>
      <button className={styles.card} onClick={setProgress}>
            set2
          </button>
      </footer>
    </div>
  )
}
