import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Script from 'next/script'

export default function Home() {
  const [progress, setProgress] = useState("-")

  return (
    <div className={styles.container}>
      <Head>
        <title>S³</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script 
        id="stripe-js"
        onLoad={() => {
          setProgress(localStorage.getItem("progress"))
        }}      
      />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Začátek pátrání
        </h1>

        <p className={styles.description}>
            Získej artefakt, máš 30 minut, jinak o něj přijdeš! Můžeš požádat o pomoc a můžeš používat nástroje, nesmí se ti ale vzorek rozdělit na více dílů!
        </p>
        <h3>Heslo artefaktu</h3>
        <div>
            <label>heslo #</label>
            <input type="text"/>
            <button >Potvrdit</button>
        </div>
      </main>
      <footer className={styles.footer}>
      <a
        href="./">
          Zpět
        </a>
      </footer>
    </div>
  )
}
