import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Script from 'next/script'

export default function Home() {
  const [progress, setProgress] = useState("-")

  return (
    <div className={styles.container}>
      <Head>
        <title>S³</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script 
        id="stripe-js"
        onLoad={() => {
          setProgress(localStorage.getItem("progress"))
        }}      
      />

      <main className={styles.main}>

        
        <img src="https://api.hunter.games/api/resources/492010d315add0c0e8381b16036438d8.jpeg">
        </img>
        <h1 className={styles.title}>
        Loupež v muzeu
        </h1>
        <p className={styles.descriptionleft}>

        Ve východočeském muzeu se koná unikátní výstava historických šperků na kterou se sjíždí lidé z celé Evropy. Dnes byl z výstavy odcizen nejcennější exponát - originál náhrdelníku královny Elišky.

Tvůj tým agentů z Bezpečnostní informační agentury byl povolán na místo činu, aby objasnil zmizení tohoto skvostu. Máš dostatečné schopnosti na to, abys dopadl zloděje a získal náhrdelník zpět?
</p>
<h2>Jak to funguje?</h2>
        <p className={styles.descriptionleft}>
V této dobrodružné detektivní hře budeš řešit sérii hádanek a šifer, které tě povedou zákoutími historického centra Hradce Králové.

Budeš hrát venku s pomocí aplikace ve svém chytrém mobilním telefonu.

Pokud si nebudeš vědět rady, máš k dispozici hned několik nápověd. Ale za každou použitou nápovědu ti bude připočten trestný čas.

Cílem hry je vyřešit případ v co nejkratším čase.
</p>
<h2>Detaily hry</h2>
        <p className={styles.descriptionleft}>
          <ul>
            <li>
          Místo startu: 
          <a href="https://www.google.com/maps/place//data=!4m2!3m1!1s0x470c2b2e67d23c2b:0x76c9e726dd9ee99a?source=g.page.default">
             Muzeum východních Čech v Hradci Králové 
             </a>
          </li>
          <li>
Délka hry: 3 hodiny
</li>
          <li>
Délka trasy: 3 km
</li>
          <li>
Lokalita: historické centrum Hradce Králové
</li>
          <li>
Obtížnost: pokročilý
</li>
          <li>
Jazyk hry: česky ( English)
</li>
          <li>
Co s sebou: nabitý mobilní telefon, mobilní internet, tužku a papír (na řešení šifer a poznámky), náhradní mobilní telefon nebo powerbanka výhodou, sluchátka výhodou (hra obsahuje poslechovou šifru)
</li>
          <li>
Kdy začít: kdykoliv, je to jen na tobě
</li>
          <li>
Autor hry: District 5 | Board Games ~ Coffee ~ Drinks
</li>
          </ul>

        </p>










      </main>
      <footer className={styles.footer}>
      <a
        href="./">
          Zpět
        </a>
      </footer>
    </div>
  )
}
